import Link from "next/link";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-[#0F172A] text-slate-300 selection:bg-amber-500 selection:text-black py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto">
        
        {/* Back Button */}
        <div className="mb-12">
          <Link href="/" className="inline-flex items-center text-sm font-mono text-amber-500 hover:text-amber-400 transition-colors">
            <span className="mr-2">←</span> RETURN TO MAIN OPERATIONS
          </Link>
        </div>

        {/* Header */}
        <div className="mb-12 border-b border-slate-800 pb-8">
          <h1 className="text-3xl sm:text-4xl font-black text-white tracking-tight mb-2">Terms of Service</h1>
          <p className="text-sm font-mono text-slate-500 uppercase tracking-widest">Effective Date: May 2026</p>
        </div>

        {/* Legal Content */}
        <div className="space-y-8 text-sm leading-relaxed text-slate-400">
          
          <section>
            <h2 className="text-xl font-bold text-white mb-4">1. Binding Agreement & Entity Acknowledgment</h2>
            <p>
              These Terms of Service ("Terms") constitute a legally binding agreement between you and Amber Rai Kalia (operating under the brand "VanshWealth"). By accessing the application, you agree to be bound by these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">2. Strictly Educational; Explicit Disclaimer of Financial Advice</h2>
            <p className="mb-4">
              VanshWealth is a mathematical utility, data visualizer, and organizational tool. Amber Rai Kalia and VanshWealth are <strong>NOT</strong> registered investment advisors, brokers, or financial planners with SEBI, RBI, IRDAI, or any global financial regulatory authority.
            </p>
            <p className="mb-4">
              The outputs generated by the "AI Cortex," "Loan Hub," "Debt Snowball," and all internal calculators are purely mathematical simulations based on user input.
            </p>
            <p>
              They do not constitute personalized financial, tax, or legal advice. You must consult a certified financial professional before executing any real-world financial strategy.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">3. Limitation of Liability and "As-Is" Provision</h2>
            <p className="mb-4">
              The application is provided on an "AS IS" and "AS AVAILABLE" basis. To the maximum extent permitted by law, VanshWealth disclaims all warranties, express or implied. Under no circumstances shall VanshWealth or Amber Rai Kalia be held liable for any direct, indirect, incidental, or consequential damages, including but not limited to:
            </p>
            <ul className="space-y-3 pl-4 border-l-2 border-slate-800 ml-2">
              <li>
                <strong className="text-slate-200 block">Financial Losses</strong>
                Debt defaults, or poor investment outcomes based on app projections.
              </li>
              <li>
                <strong className="text-slate-200 block">Data Loss</strong>
                Inability to recover funds based on the "Red Folder" legacy vault.
              </li>
              <li>
                <strong className="text-slate-200 block">Market Discrepancies</strong>
                Discrepancies between app projections and live banking or market realities.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">4. Intellectual Property & Nominative Fair Use</h2>
            <p>
              All proprietary algorithms, UI designs, and code within VanshWealth are the exclusive intellectual property of Amber Rai Kalia. Any mention of third-party entities, banks, insurance companies, or mutual funds within the app is strictly for nominative identification and educational comparison. VanshWealth claims no affiliation with or endorsement by these trademark holders.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-4">5. Governing Law & Jurisdiction</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the Republic of India. Any disputes arising from or in connection with these Terms, the application, or billing matters shall be subject to the exclusive jurisdiction of the competent courts located in Jammu, India.
            </p>
          </section>
          
        </div>
        
      </div>
    </div>
  );
}